routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Admin Url 
Route::get('/admin/login', 'Admin\AdminLoginController@index')->name('admin');
Route::post('/admin/dastboard', 'Admin\AdminLoginController@login')->name('admin');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::group(['prefix' =>'product', 'as' => 'product.' ], function(){
        Route::resource('/categories','Admin\Product\CategoriesController');
        Route::resource('/sub-categories','Admin\Product\SubCategoriesController');
        Route::resource('/attributes','Admin\Product\ProductAttributeController');
        //In product image controller update and store function are exchnage, 
        //update function work as store new data and store function work as update data
        Route::resource('/images','Admin\Product\ProductImageController');
        Route::get('/image/create/{id}','Admin\Product\ProductImageController@productImageCreate')->name('image.create');


    });
    Route::resource('/products','Admin\Product\ProductController');
    Route::resource('/term-and-conditions','Admin\TermAndConditionController');
    Route::resource('/orders','Admin\OrderController');
    Route::resource('/banner-ad-images','Admin\BannerAdImageController');
    Route::resource('/customers','Admin\CustomerController');
    Route::resource('/customer-cards','Admin\CustomerCardsController');
});
//Frontend Url
Route::get('categories\{id}', 'Frontend\FrontendController@getCategoryData')->name('categories');
Route::get('sub-categories\{id}', 'Frontend\FrontendController@getsubCategoryData')->name('sub-categories');
Route::get('products\{id}', 'Frontend\FrontendController@getSingleProduct')->name('products');
Route::get('about-us', 'Frontend\FrontendController@aboutUs')->name('about-us');
Route::get('contact-us', 'Frontend\FrontendController@contactUs')->name('contact-us');
Route::get('blogs', 'Frontend\FrontendController@getBlog')->name('blogs');


//Customer Login/Sign Up URL
Route::get('customer/login', 'Frontend\CustomerController@getLoginForm')->name('customer.login');
Route::post('customer/dastboard', 'Frontend\CustomerController@login')->name('customer.dastboard');
Route::get('customer/sign-up', 'Frontend\CustomerController@getSignUpForm')->name('customer.sign-up');
Route::post('customer/sign-up', 'Frontend\CustomerController@SignUp')->name('customer.sign-up');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $fillable=['product_category_id','product_sub_category_id','product_name','description ','status','created_by','updated_by'];

    public function ProductCategories(){
        return $this->belongsTo(ProductCategory::class, 'product_category_id')->withDefault();
    }
    public function ProductSubCategory(){
        return $this->belongsTo(ProductSubCategory::class, 'product_sub_category_id')->withDefault();
    }
    public function productAttribute(){
        return $this->hasMany(ProductAttribute::class, 'product_id');
    }
    public function productImage(){
        return $this->hasMany(ProductImage::class, 'product_id');
    }
    public function orderProduct(){
        return $this->hasMany(Order::class, 'product_name');
    }
}

app/Http/Controllers/Admin/Product/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Models\ProductCategory;
use Illuminate\Http\Request;
use App\Repositories\ProductCategory\ProductCategoryInterface;
use App\ValidationRules\ProductCategoryRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use DB;

class CategoriesController extends Controller
{
    private $productCategoryReopsitories;

    public function __construct(ProductCategoryInterface $productCategoryReopsitories){
            $this->productCategoryReopsitories=$productCategoryReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $productCategory=$this->productCategoryReopsitories->all();
        return view('admin.pages.product.categories.index')->with('productCategories', $productCategory);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.product.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductCategoryRule($request))->getProductCategoryRules('create'));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->except('_token');
        $productCategoryStore=$this->productCategoryReopsitories->store($data);
        DB::commit();
        session()->flash('flash_message_success','Data Store Successfuly!!');
        return redirect()->route('admin.product.categories.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productCategory=$this->productCategoryReopsitories->findById($id);
        return \view('admin.pages.product.categories.edit')->with('productCategories', $productCategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new ProductCategoryRule($request))->getProductCategoryRules('update', $id));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $updateProductCategory=$this->productCategoryReopsitories->update($data, $id);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.product.categories.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Product/ProductAttributeController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Product\ProductInterface;
use App\ValidationRules\ProductAttributeRule;
use Illuminate\Support\Facades\Validator;
use DB;


class ProductAttributeController extends Controller
{
    private $productReopsitories;

    public function __construct(ProductInterface $productReopsitories){
            $this->productReopsitories=$productReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.product.product-attribute.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductAttributeRule($request))->getProductAttributeRules('create'));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $storeProductAttribute=$this->productReopsitories->productAttributeStore($data);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.products.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $productAttribute=$this->productReopsitories->productAttributeList($id);
        return \view('admin.pages.product.product-attribute.show')->with('productAttributes', $productAttribute);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productAttribute=$this->productReopsitories->productAttributeList($id);
        return \view('admin.pages.product.product-attribute.edit')->with('productAttributes', $productAttribute);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $productAttributeDelete=$this->productReopsitories->productAttributeDelete($id);
        return \redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Product\ProductInterface;
use App\ValidationRules\ProductRule;
use Illuminate\Support\Facades\Validator;
use DB;

class ProductController extends Controller
{
    
    private $productReopsitories;

    public function __construct(ProductInterface $productReopsitories){
            $this->productReopsitories=$productReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $product=$this->productReopsitories->all();
        return \view('admin.pages.product.products.index')->with('products', $product);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $productCategory=$this->productReopsitories->productCategory();
        $productSubCategory=$this->productReopsitories->productSubCategory();
        return \view('admin.pages.product.products.create')
                    ->with('productCategories', $productCategory)
                    ->with('productSubCategories', $productSubCategory);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductRule($request))->getProductRules('create'));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $storeProduct=$this->productReopsitories->store($data);
        DB::commit();
        session()->flash('flash_message_success','Data Store Successfuly!!');
        return redirect()->route('admin.products.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $product=$this->productReopsitories->findById($id);
        $productAttribute=$this->productReopsitories->productAttribute($id);
        $productImage=$this->productReopsitories->productImage($id);
        return \view('admin.pages.product.products.show')
                        ->with('productAttributes', $productAttribute)
                        ->with('productImages', $productImage)
                        ->with('products', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productCategory=$this->productReopsitories->productCategory();
        $productSubCategory=$this->productReopsitories->productSubCategory();
        $products=$this->productReopsitories->findById($id);
        return \view('admin.pages.product.products.edit')
                    ->with('productCategories', $productCategory)
                    ->with('productSubCategories' , $productSubCategory)
                    ->with('product', $products);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new ProductRule($request))->getProductRules('update', $id));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $updateProduct=$this->productReopsitories->update($data, $id);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return redirect()->route('admin.products.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function productAttributeList($productId){
        $productAttribute=$this->productReopsitories->productAttributeList($productId);
        return $productAttribute;
    }
}

resources/views/admin/pages/product/products/create.blade.php
@extends('admin.layouts.app')

@section('content')
				<div class="span9">
					<div class="content">
						<div class="module">
							<div class="module-head">
								<h3>Create</h3>
							</div>
							<div class="module-body">
							@include('error-messages.message')
									<form class="form-horizontal row-fluid" action="{{route('admin.products.store')}}" method="POST" enctype="multipart/form-data" >
											{{ csrf_field() }}
											
											<div class="control-group">
											<label class="control-label" for="basicinput">Category</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="product_category_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($productCategories as $productCategory)
													<option value="{{$productCategory->id}}" {{ (old ('product_category_id')==$productCategory->id)? "selected" : ''}} >{{$productCategory->product_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>
										
										<div class="control-group">
											<label class="control-label" for="basicinput">Category</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="product_sub_category_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($productSubCategories as $productSubCategory)
													<option value="{{$productSubCategory->id}}" {{ (old ('product_sub_category_id')==$productSubCategory->id)? "selected" : ''}} >{{$productSubCategory->product_sub_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>										
                                            <div class="control-group">
											<label class="control-label" for="basicinput">Category Name</label>
											<div class="controls">
												<input type="text" name="product_name" id="basicinput" placeholder="Type Product Name here..." class="span8" value="{{old('product_category_name')}}">
											</div>
										</div>		
										<div class="control-group">
											<label class="control-label" for="basicinput">Price($)</label>
											<div class="controls">
												<input type="text" name="main_price" id="basicinput" placeholder="Type Price  here..." class="span8" value="{{old('main_price')}}">
											</div>
										</div>		
										<div class="control-group">
											<label class="control-label" for="basicinput">Thump Image</label>
											<div class="controls">
												<input type="file" name="thump_images" id="basicinput" placeholder="Type Product Name here..." class="span8" value="{{old('thump_images')}}" required>
											</div>
                                        </div>											
										<div class="control-group">
											<label class="control-label">Status</label>
											<div class="controls">
												<label class="radio">
													<input type="radio" name="status" id="optionsRadios1" value="1" {{(old('status')=='1') ? 'checked' : ''}}>
													Active
												</label> 
												<label class="radio">
													<input type="radio" name="status" id="optionsRadios2" value="0" {{(old('status')=='0') ? 'checked' : ''}}>
													Deactive
												</label> 
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Description</label>
											<div class="controls">
												<textarea class="span8" rows="5" name="description">{{Request::old('description')}}  </textarea>
											</div>
										</div>

										<div class="control-group">
											<div class="controls">
												<button type="submit" class="btn btn-primary">Create  </button>
											</div>
										</div>
									</form>
							</div>
						</div>	
					</div><!--/.content-->
                </div><!--/.span9-->
        @endsection

resources/views/admin/pages/product/products/edit.blade.php
@extends('admin.layouts.app')

@section('content')
				<div class="span9">
					<div class="content">

						<div class="module">
							<div class="module-head">
								<h3>Update</h3>
							</div>
							<div class="module-body">
							@include('error-messages.message')
									<form class="form-horizontal row-fluid" action="{{route('admin.products.update', $product->id)}}" method="POST" enctype="multipart/form-data" >
                                            {{ csrf_field() }}	
                                            <input type="hidden" name="_method" value="PUT">
											<div class="control-group">
											<label class="control-label" for="basicinput">Category</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="product_category_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($productCategories as $productCategory)
													<option value="{{$productCategory->id}}" {{($product->product_category_id == $productCategory->id) ? 'selected' : ''}}  >{{$productCategory->product_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>			
										<div class="control-group">
											<label class="control-label" for="basicinput">Sub Category</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="product_sub_category_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($productSubCategories as $productSubCategory)
													<option value="{{$productSubCategory->id}}" {{($product->product_sub_category_id == $productSubCategory->id) ? 'selected' : ''}} >{{$productSubCategory->product_sub_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>			
                                            <div class="control-group">
											<label class="control-label" for="basicinput">Product Name</label>
											<div class="controls">
												<input type="text" name="product_name" id="basicinput" placeholder="Type Product Name here..." class="span8" value="{{$product->product_name}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Price($)</label>
											<div class="controls">
												<input type="text" name="main_price" id="basicinput" placeholder="Type  here..." class="span8" value="{{$product->main_price}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Thump Image</label>
											<div class="controls">
												<input type="file" name="thump_images" id="basicinput" placeholder="Type Product Name here..." class="span8" value="{{$product->thump_images}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label">Status</label>
											<div class="controls">
												<label class="radio">
                                                <input type="radio" class="custom-control-input" id="defaultChecked" name="status"  value="1" {{$product->status == 1 ? 'checked' : '' }} >
													Active
												</label> 
												<label class="radio">
                                                <input type="radio" class="custom-control-input" id="defaultUnchecked" name="status" value="0" {{$product->status == 0 ? 'checked' : '' }} >
													Deactive
												</label> 
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Description</label>
											<div class="controls">
												<textarea class="span8" rows="5" name="description">{{$product->description}}</textarea>
											</div>
										</div>

										<div class="control-group">
											<div class="controls">
												<button type="submit" class="btn btn-primary">Update  </button>
											</div>
										</div>
									</form>
							</div>
						</div>	
					</div><!--/.content-->
                </div><!--/.span9-->
        @endsection

resources/views/admin/pages/product/products/index.blade.php
@extends('admin.layouts.app')
@section('title','Product Category')
@section('content')


					<div class="row">
						<div class="col-lg-12" style="text-align: right;">
					<a href="{{route('admin.products.create')}}" class="btn btn-info">Create New Product </a>
						</div>
					</div>
						<div class="module">
							<div class="module-head">
								<h3>Product list</h3>
							</div>
							<div class="module-body table">
							@include('error-messages.message')

								<table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display" width="100%">
									<thead>
										<tr>
											<th>Product Name</th>
											<th>Status</th>
											<th>Action</th>
											<th>Attribute Action</th>
											<th>Image Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach($products as $product)
										<tr class="odd gradeX">
											<td>{{ $product->product_name }}</td>
											<td>
												@if($product->status==1)
												Active
												@else
												Deactivate
												@endif
											</td>
											<td>
												<a href="{{route('admin.products.show', $product->id)}}" class="btn btn-info">View</a>
												<a href="{{route('admin.products.edit', $product->id)}}" class="btn btn-primary">Edit</a>

											</td>
											<td>
												<a href="{{route('admin.product.attributes.show', $product->id)}}" class="btn btn-info">View</a>
												<a href="{{route('admin.product.attributes.edit', $product->id)}}" class="btn btn-primary">Create/Edit</a>

											</td>
											<td>
												<a href="{{route('admin.product.image.create', $product->id)}}" class="btn btn-primary">create</a>
												<a href="{{route('admin.product.images.show', $product->id)}}" class="btn btn-info">View</a>
												<a href="{{route('admin.product.images.edit', $product->id)}}" class="btn btn-primary">Edit</a>


											</td>
										</tr>	
										@endforeach
									</tbody>
								</table>
							</div>
						</div><!--/.module-->

					<br />
@endsection