routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Admin Url 
Route::get('/admin/login', 'Admin\AdminLoginController@index')->name('admin');
Route::post('/admin/dastboard', 'Admin\AdminLoginController@login')->name('admin');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::group(['prefix' =>'product', 'as' => 'product.' ], function(){
        Route::resource('/categories','Admin\Product\CategoriesController');
        Route::resource('/sub-categories','Admin\Product\SubCategoriesController');
        Route::resource('/attributes','Admin\Product\ProductAttributeController');
        //In product image controller update and store function are exchnage, 
        //update function work as store new data and store function work as update data
        Route::resource('/images','Admin\Product\ProductImageController');
        Route::get('/image/create/{id}','Admin\Product\ProductImageController@productImageCreate')->name('image.create');


    });
    Route::resource('/products','Admin\Product\ProductController');
    Route::resource('/term-and-conditions','Admin\TermAndConditionController');
    Route::resource('/orders','Admin\OrderController');
    Route::resource('/banner-ad-images','Admin\BannerAdImageController');
    Route::resource('/customers','Admin\CustomerController');
    Route::resource('/customer-cards','Admin\CustomerCardsController');
});
//Frontend Url
Route::get('categories\{id}', 'Frontend\FrontendController@getCategoryData')->name('categories');
Route::get('sub-categories\{id}', 'Frontend\FrontendController@getsubCategoryData')->name('sub-categories');
Route::get('products\{id}', 'Frontend\FrontendController@getSingleProduct')->name('products');
Route::get('about-us', 'Frontend\FrontendController@aboutUs')->name('about-us');
Route::get('contact-us', 'Frontend\FrontendController@contactUs')->name('contact-us');
Route::get('blogs', 'Frontend\FrontendController@getBlog')->name('blogs');


//Customer Login/Sign Up URL
Route::get('customer/login', 'Frontend\CustomerController@getLoginForm')->name('customer.login');
Route::post('customer/dastboard', 'Frontend\CustomerController@login')->name('customer.dastboard');
Route::get('customer/sign-up', 'Frontend\CustomerController@getSignUpForm')->name('customer.sign-up');
Route::post('customer/sign-up', 'Frontend\CustomerController@SignUp')->name('customer.sign-up');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
    public function orderProduct(){
        return $this->belongsTo(Product::class, 'product_name');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderPayment;
use Illuminate\Http\Request;
use DB;

class OrderController extends Controller
{
    public function __construct(){
        $this->middleware('Admin');

}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $order=Order::with('orderProduct')->get();
        return \view('admin.pages.order.index')->with('orders', $order);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $orderList=Order::find($id);
        return \view('admin.pages.order.edit')->with("order_list", $orderList);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        DB::beginTransaction();
        try{
        $updateStatus=Order::find($id);
        $updateStatus->status=$request->status;
        $updateStatus->save();
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.orders.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function paymentDetail($id){

        // $paymentDetails=OrderPayment::where()
    }
}

resources/views/admin/pages/order/edit.blade.php
@extends('admin.layouts.app')

@section('content')
				<div class="span9">
					<div class="content">

						<div class="module">
							<div class="module-head">
								<h3>Update</h3>
							</div>
							<div class="module-body">
							@include('error-messages.message')
									<form class="form-horizontal row-fluid" action="{{route('admin.orders.update', $order_list->id)}}" method="POST" enctype="multipart/form-data" >
                                            {{ csrf_field() }}	
                                            <input type="hidden" name="_method" value="PUT">

											<div class="control-group">
											<label class="control-label" for="basicinput">Status</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="status">
													<option value="">Select here..</option>
                                                    <option value="approved" >Approved</option>
                                                    <option value="panding" >Panding</option>
                                                    <option value="complet" >Complet</option>

												</select>
											</div>
										</div>

										<div class="control-group">
											<div class="controls">
												<button type="submit" class="btn btn-primary">Update </button>
											</div>
										</div>
									</form>
							</div>
						</div>	
					</div><!--/.content-->
                </div><!--/.span9-->
        @endsection

resources/views/admin/pages/order/index.blade.php
@extends('admin.layouts.app')
@section('title','Product Category')
@section('content')

						<div class="module">
							<div class="module-head">
								<h3>Order list</h3>
							</div>
							<div class="module-body table">
							@include('error-messages.message')

								<table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display" width="100%">
									<thead>
										<tr>
											<th>User Id</th>
											<th>Product Name</th>
											<th>Status</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach($orders as $order)
										<tr class="odd gradeX">
											<td>{{ $order->order_user_id }}</td>
											<td>{{$order->orderProduct->product_name}}</td>
											<td>
												@if($order->status=="panding")
												Panding
												@elseif($order->status=="approved")
												Approved
												@else
												Complet
												@endif
											</td>
											<td>
												<a href="{{route('admin.orders.edit', $order->id)}}" class="btn btn-info">View Payment</a>
												<a href="{{route('admin.orders.edit', $order->id)}}" class="btn btn-info">Change The Status</a>
											</td>
										</tr>	
										@endforeach
									</tbody>
								</table>
							</div>
						</div><!--/.module-->

					<br />
@endsection