routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Admin Url 
Route::get('/admin/login', 'Admin\AdminLoginController@index')->name('admin');
Route::post('/admin/dastboard', 'Admin\AdminLoginController@login')->name('admin');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::group(['prefix' =>'product', 'as' => 'product.' ], function(){
        Route::resource('/categories','Admin\Product\CategoriesController');
        Route::resource('/sub-categories','Admin\Product\SubCategoriesController');
        Route::resource('/attributes','Admin\Product\ProductAttributeController');
        //In product image controller update and store function are exchnage, 
        //update function work as store new data and store function work as update data
        Route::resource('/images','Admin\Product\ProductImageController');
        Route::get('/image/create/{id}','Admin\Product\ProductImageController@productImageCreate')->name('image.create');


    });
    Route::resource('/products','Admin\Product\ProductController');
    Route::resource('/term-and-conditions','Admin\TermAndConditionController');
    Route::resource('/orders','Admin\OrderController');
    Route::resource('/banner-ad-images','Admin\BannerAdImageController');
    Route::resource('/customers','Admin\CustomerController');
    Route::resource('/customer-cards','Admin\CustomerCardsController');
});
//Frontend Url
Route::get('categories\{id}', 'Frontend\FrontendController@getCategoryData')->name('categories');
Route::get('sub-categories\{id}', 'Frontend\FrontendController@getsubCategoryData')->name('sub-categories');
Route::get('products\{id}', 'Frontend\FrontendController@getSingleProduct')->name('products');
Route::get('about-us', 'Frontend\FrontendController@aboutUs')->name('about-us');
Route::get('contact-us', 'Frontend\FrontendController@contactUs')->name('contact-us');
Route::get('blogs', 'Frontend\FrontendController@getBlog')->name('blogs');


//Customer Login/Sign Up URL
Route::get('customer/login', 'Frontend\CustomerController@getLoginForm')->name('customer.login');
Route::post('customer/dastboard', 'Frontend\CustomerController@login')->name('customer.dastboard');
Route::get('customer/sign-up', 'Frontend\CustomerController@getSignUpForm')->name('customer.sign-up');
Route::post('customer/sign-up', 'Frontend\CustomerController@SignUp')->name('customer.sign-up');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $fillable=['product_category_id','product_sub_category_id','product_name','description ','status','created_by','updated_by'];

    public function ProductCategories(){
        return $this->belongsTo(ProductCategory::class, 'product_category_id')->withDefault();
    }
    public function ProductSubCategory(){
        return $this->belongsTo(ProductSubCategory::class, 'product_sub_category_id')->withDefault();
    }
    public function productAttribute(){
        return $this->hasMany(ProductAttribute::class, 'product_id');
    }
    public function productImage(){
        return $this->hasMany(ProductImage::class, 'product_id');
    }
    public function orderProduct(){
        return $this->hasMany(Order::class, 'product_name');
    }
}

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    //
    protected $fillable=['product_id','product_attribute_id','images','created_by','updated_by'];

    public function productImage(){
        return $this->belongsTo(Product::class, 'product_id')->withDefault();
    }
    public function productImageAttribute(){
        return $this->belongsTo(ProductAttribute::class, 'product_attribute_id')->withDefault();
    }
}

app/Http/Controllers/Admin/Product/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use App\Models\ProductCategory;
use Illuminate\Http\Request;
use App\Repositories\ProductCategory\ProductCategoryInterface;
use App\ValidationRules\ProductCategoryRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use DB;

class CategoriesController extends Controller
{
    private $productCategoryReopsitories;

    public function __construct(ProductCategoryInterface $productCategoryReopsitories){
            $this->productCategoryReopsitories=$productCategoryReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $productCategory=$this->productCategoryReopsitories->all();
        return view('admin.pages.product.categories.index')->with('productCategories', $productCategory);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.product.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductCategoryRule($request))->getProductCategoryRules('create'));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->except('_token');
        $productCategoryStore=$this->productCategoryReopsitories->store($data);
        DB::commit();
        session()->flash('flash_message_success','Data Store Successfuly!!');
        return redirect()->route('admin.product.categories.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productCategory=$this->productCategoryReopsitories->findById($id);
        return \view('admin.pages.product.categories.edit')->with('productCategories', $productCategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new ProductCategoryRule($request))->getProductCategoryRules('update', $id));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $updateProductCategory=$this->productCategoryReopsitories->update($data, $id);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.product.categories.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Product/ProductAttributeController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Product\ProductInterface;
use App\ValidationRules\ProductAttributeRule;
use Illuminate\Support\Facades\Validator;
use DB;


class ProductAttributeController extends Controller
{
    private $productReopsitories;

    public function __construct(ProductInterface $productReopsitories){
            $this->productReopsitories=$productReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.product.product-attribute.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductAttributeRule($request))->getProductAttributeRules('create'));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $storeProductAttribute=$this->productReopsitories->productAttributeStore($data);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.products.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $productAttribute=$this->productReopsitories->productAttributeList($id);
        return \view('admin.pages.product.product-attribute.show')->with('productAttributes', $productAttribute);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productAttribute=$this->productReopsitories->productAttributeList($id);
        return \view('admin.pages.product.product-attribute.edit')->with('productAttributes', $productAttribute);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $productAttributeDelete=$this->productReopsitories->productAttributeDelete($id);
        return \redirect()->back();
    }
}

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Product\ProductInterface;
use App\ValidationRules\ProductRule;
use Illuminate\Support\Facades\Validator;
use DB;

class ProductController extends Controller
{
    
    private $productReopsitories;

    public function __construct(ProductInterface $productReopsitories){
            $this->productReopsitories=$productReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $product=$this->productReopsitories->all();
        return \view('admin.pages.product.products.index')->with('products', $product);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $productCategory=$this->productReopsitories->productCategory();
        $productSubCategory=$this->productReopsitories->productSubCategory();
        return \view('admin.pages.product.products.create')
                    ->with('productCategories', $productCategory)
                    ->with('productSubCategories', $productSubCategory);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new ProductRule($request))->getProductRules('create'));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $storeProduct=$this->productReopsitories->store($data);
        DB::commit();
        session()->flash('flash_message_success','Data Store Successfuly!!');
        return redirect()->route('admin.products.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $product=$this->productReopsitories->findById($id);
        $productAttribute=$this->productReopsitories->productAttribute($id);
        $productImage=$this->productReopsitories->productImage($id);
        return \view('admin.pages.product.products.show')
                        ->with('productAttributes', $productAttribute)
                        ->with('productImages', $productImage)
                        ->with('products', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $productCategory=$this->productReopsitories->productCategory();
        $productSubCategory=$this->productReopsitories->productSubCategory();
        $products=$this->productReopsitories->findById($id);
        return \view('admin.pages.product.products.edit')
                    ->with('productCategories', $productCategory)
                    ->with('productSubCategories' , $productSubCategory)
                    ->with('product', $products);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new ProductRule($request))->getProductRules('update', $id));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $updateProduct=$this->productReopsitories->update($data, $id);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return redirect()->route('admin.products.index');
        }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function productAttributeList($productId){
        $productAttribute=$this->productReopsitories->productAttributeList($productId);
        return $productAttribute;
    }
}

resources/views/admin/pages/product/product-images/create.blade.php
@extends('admin.layouts.app')
@section('title','Product Attribute')
@section('content')
@include('error-messages.message')

<table class="table table-striped table-bordered table-condensed">
								  <thead>
									<tr>
									  <th>#</th>
									  <th>Product Attribute  </th>
									</tr>
								  </thead>
								  <tbody>
                          <form action="{{route('admin.product.images.update', $productId)}}" method="POST" enctype="multipart/form-data">
						  {{ csrf_field() }}
						  <input type="hidden" name="_method" value="PUT">
									<tr>								 
									   <td>
										  <select name="product_attribute_id[]">
											  @foreach($productAttributes as $productAttribute )
											  <option value="{{$productAttribute->id}}" >{{$productAttribute->color}}</option>
											  @endforeach
										  </select>
									  </td>
									  <td><input type="file"  name="productImage[]" required></td>
                           </tr>
								  </tbody>
                        </table>                        
                        <div class="form-group">
                        <input type="submit" id="submitted"  class="btn btn-success" value="create">
                        </div>

                </form>
							</div>
                  </div>
                  @endsection

resources/views/admin/pages/product/product-images/edit.blade.php
@extends('admin.layouts.app')
@section('title','Product Attribute')
@section('content')
@include('error-messages.message')

<table class="table table-striped table-bordered table-condensed">
								  <thead>
									<tr>
									  <th>#</th>
									  <th>Product Attribute  </th>
									  <th>Image</th>
									</tr>
								  </thead>
								  <tbody>
                          <form action="{{route('admin.product.images.store')}}" method="POST" enctype="multipart/form-data">
                          {{ csrf_field() }}	
                             @foreach($productImages as $productImage)
									<tr>
									  <td>{{$loop->iteration}}</td>
									  <input type="hidden" value="{{$productImage->id}}" name="id[]">
									  <input type="hidden" value="{{$productImage->product_id}}" name="product_id[]">
									  <td>
										  <select name="product_attribute_id[]">
											  @foreach($productAttributes as $productAttribute )
											  <option value="{{$productAttribute->id}}" {{($productAttribute->id == $productImage->product_attribute_id) ? 'selected' : ''}}>{{$productAttribute->color}}</option>
											  @endforeach
										  </select>
									  </td>
									  <?php $url=url('productImage/'.$productImage->images); 
                                				?>
									  <td><input type="file" value="{{$productImage->images}}" name="productImage[]"></td>
									  <td>
									  <a href="{{ asset('/productImage/' .$productImage->images)}}"><img class="d-block w-100" src="{{$url}}"  alt="Snow" height="100px" width="100px"></a>
									  </td>
                           </tr>
                           @endforeach
								  </tbody>
                        </table>                        
                        <div class="form-group">
                        <input type="submit" id="submitted"  class="btn btn-success" value="Update">
                        </div>

                </form>
							</div>
                  </div>
                  @endsection

resources/views/admin/pages/product/product-images/script.blade.php
<script>  
 $(document).ready(function(){  
      var i=1;  
      $('#add').click(function(){  
           i++;  
           $('#dynamic_field').append('<tr id="row'+i+'"><td><input type="number" name="min_weight[]" placeholder="Enter  minimum weight" class="form-control min-weight"/></td><td><input type="number" name="max_weight[]" placeholder="Enter maxmium weight" class="form-control max-weight"/></td><br><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
      });  
      $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      });  
    
 });  
 </script>

resources/views/admin/pages/product/product-images/show.blade.php
@extends('admin.layouts.app')
@section('title','Product Attribute')
@section('content')
<div>
        <h5 style="text-align: center;">Product Images</h5>
	</div>
	<div class="span9">
                    <div class="content">
                        <div class="module">
                            <div class="module-body">
                                @if($productImages->isEmpty())
                                No Record Found
                                @endif
								@foreach($productImages as $productImage)

                                <div class="row-fluid">
                                    <div class="span12">
                                        <div class="media user">
                                        <?php $url=url('productImage/'.$productImage->images); 
                                				?>
                                            <a class="media-avatar pull-left" href="{{ asset('/productImage/' .$productImage->images)}}">
                                                <img src="{{$url}}">
                                            </a>
                                            <div class="media-body">
                                                <table class="table" align="center" style="width: 70%;">
                                                        <tr>
                                                            <th>Size</th>
                                                            <td>{{$productImage->productImageAttribute->size}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th>Color</th>
                                                            <td>{{$productImage->productImageAttribute->color}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th>Price</th>
                                                            <td>Rs.{{$productImage->productImageAttribute->price}}</td>
														</tr>
														<tr>
                                                            <th>Action</th>
                                                            <td>
															{!! Form::open(['route' => ['admin.product.images.destroy', $productImage->id], 'method' => 'delete']) !!}

															{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

															{!! Form::close() !!}
															</td>
                                                        </tr>
                                                    </table>
											</div>
                                        </div>
									</div>
									
								</div>

                                <!--/.row-fluid-->
								<br />
								@endforeach

							</div>

                        </div>
					</div>

                    <!--/.content-->
				</div>

                <!--/.span9-->
                        @endsection