routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Admin Url 
Route::get('/admin/login', 'Admin\AdminLoginController@index')->name('admin');
Route::post('/admin/dastboard', 'Admin\AdminLoginController@login')->name('admin');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::group(['prefix' =>'product', 'as' => 'product.' ], function(){
        Route::resource('/categories','Admin\Product\CategoriesController');
        Route::resource('/sub-categories','Admin\Product\SubCategoriesController');
        Route::resource('/attributes','Admin\Product\ProductAttributeController');
        //In product image controller update and store function are exchnage, 
        //update function work as store new data and store function work as update data
        Route::resource('/images','Admin\Product\ProductImageController');
        Route::get('/image/create/{id}','Admin\Product\ProductImageController@productImageCreate')->name('image.create');


    });
    Route::resource('/products','Admin\Product\ProductController');
    Route::resource('/term-and-conditions','Admin\TermAndConditionController');
    Route::resource('/orders','Admin\OrderController');
    Route::resource('/banner-ad-images','Admin\BannerAdImageController');
    Route::resource('/customers','Admin\CustomerController');
    Route::resource('/customer-cards','Admin\CustomerCardsController');
});
//Frontend Url
Route::get('categories\{id}', 'Frontend\FrontendController@getCategoryData')->name('categories');
Route::get('sub-categories\{id}', 'Frontend\FrontendController@getsubCategoryData')->name('sub-categories');
Route::get('products\{id}', 'Frontend\FrontendController@getSingleProduct')->name('products');
Route::get('about-us', 'Frontend\FrontendController@aboutUs')->name('about-us');
Route::get('contact-us', 'Frontend\FrontendController@contactUs')->name('contact-us');
Route::get('blogs', 'Frontend\FrontendController@getBlog')->name('blogs');


//Customer Login/Sign Up URL
Route::get('customer/login', 'Frontend\CustomerController@getLoginForm')->name('customer.login');
Route::post('customer/dastboard', 'Frontend\CustomerController@login')->name('customer.dastboard');
Route::get('customer/sign-up', 'Frontend\CustomerController@getSignUpForm')->name('customer.sign-up');
Route::post('customer/sign-up', 'Frontend\CustomerController@SignUp')->name('customer.sign-up');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/BannerAdImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BannerAdImage extends Model
{
    protected $fillable=['banner_add_name','images','order','image_types','created_by','updated_by'];
    //
}

app/Http/Controllers/Admin/BannerAdImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\BannerAdImage\BannerAdImageInterface;
use App\ValidationRules\BannerAdImageRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class BannerAdImageController extends Controller
{
    private $BannerAdImageReopsitories;

    public function __construct(BannerAdImageInterface $BannerAdImageReopsitories){
            $this->BannerAdImageReopsitories=$BannerAdImageReopsitories;
            $this->middleware('Admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $bannerAdImage=$this->BannerAdImageReopsitories->all();
        return \view('admin.pages.banner-ad-images.index')->with('bannerAdImages', $bannerAdImage);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $subCategoryList=$this->BannerAdImageReopsitories->subCategoryList();
        return \view('admin.pages.banner-ad-images.create')->with('subCategoryLists', $subCategoryList);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {        
        $validator = Validator::make($request->all(),(new BannerAdImageRule($request))->getBannerAdImageRules('create'));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $bannerAdImageStore=$this->BannerAdImageReopsitories->store($data);
        DB::commit();
        session()->flash('flash_message_success','Image Store Successfuly!!');
        return \redirect()->route('admin.banner-ad-images.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $subCategoryList=$this->BannerAdImageReopsitories->subCategoryList();

        $bannerAdImage=$this->BannerAdImageReopsitories->findById($id);
        return \view('admin.pages.banner-ad-images.edit')
                    ->with('subCategoryLists', $subCategoryList)
                    ->with('bannerAdImages', $bannerAdImage);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
              
        $validator = Validator::make($request->all(),(new BannerAdImageRule($request))->getBannerAdImageRules('update', $id));

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        //
        DB::beginTransaction();
        try{
        $data=$request->all();
        $updateBannerImages=$this->BannerAdImageReopsitories->update($data, $id);
        DB::commit();
        session()->flash('flash_message_success','Data Update Successfuly!!');
        return \redirect()->route('admin.banner-ad-images.index');
    }catch (\Exception $exception){
        DB::rollback();
        return redirect()->back()
            ->withInput()
            ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/banner-ad-images/create.blade.php
@extends('admin.layouts.app')

@section('content')
				<div class="span9">
					<div class="content">
						<div class="module">
							<div class="module-head">
								<h3>Create</h3>
							</div>
							<div class="module-body">
							@include('error-messages.message')
									<form class="form-horizontal row-fluid" action="{{route('admin.banner-ad-images.store')}}" method="POST" enctype="multipart/form-data" >
                                            {{ csrf_field() }}										
                                            <div class="control-group">
											<label class="control-label" for="basicinput">Banner Name</label>
											<div class="controls">
												<input type="text" name="banner_add_name" id="basicinput" placeholder="Type Banner Name here..." class="span8" value="{{old('banner_add_name')}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Starting From($)</label>
											<div class="controls">
												<input type="number" name="price" id="basicinput" placeholder="Type here..." class="span8" value="{{old('price')}}">
											</div>
										</div>
													
										<div class="control-group">
											<label class="control-label" for="basicinput">Image</label>
											<div class="controls">
												<input type="file" name="images" id="basicinput" class="span8" value="{{old('images')}}" required>
											</div>
										</div>	

										<div class="control-group">
											<label class="control-label" for="basicinput">Image Type</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="image_types">
													<option value="" disabled selected>Select here..</option>
													<option value="banner_ad_image">Banner Ad</option>
													<option value="slider_image">Slider</option>
												</select>
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Sub Category Link Id</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="sub_category_link_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($subCategoryLists as $subCategoryList)
													<option value="{{$subCategoryList->id}}" {{ (old ('sub_category_link_id')==$subCategoryList->id)? "selected" : ''}}>{{$subCategoryList->product_sub_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Order</label>
											<div class="controls">
												<input type="number" name="order" id="basicinput" placeholder="Type Image oder here..." class="span8" value="{{old('order')}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Description</label>
											<div class="controls">
												<textarea class="span8" rows="5" name="description">{{Request::old('description')}}  </textarea>
											</div>
										</div>
										<div class="control-group">
											<div class="controls">
												<button type="submit" class="btn btn-primary">Create</button>
											</div>
										</div>
									</form>
							</div>
						</div>	
					</div><!--/.content-->
                </div><!--/.span9-->
        @endsection

resources/views/admin/pages/banner-ad-images/edit.blade.php
@extends('admin.layouts.app')

@section('content')
				<div class="span9">
					<div class="content">
						<div class="module">
							<div class="module-head">
								<h3>Edit</h3>
							</div>
							<div class="module-body">
							@include('error-messages.message')
									<form class="form-horizontal row-fluid" action="{{route('admin.banner-ad-images.update', $bannerAdImages->id)}}" method="POST" enctype="multipart/form-data" >
											{{ csrf_field() }}	
											<input type="hidden" name="_method" value="PUT">
									
                                            <div class="control-group">
											<label class="control-label" for="basicinput">Banner Name</label>
											<div class="controls">
												<input type="text" name="banner_add_name" id="basicinput" placeholder="Type Banner Name here..." class="span8" value="{{$bannerAdImages->banner_add_name}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Starting From($)</label>
											<div class="controls">
												<input type="number" name="price" id="basicinput" placeholder="Type  here..." class="span8" value="{{$bannerAdImages->price}}">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Order</label>
											<div class="controls">
												<input type="number" name="order" id="basicinput" placeholder="Type Image oder here..." class="span8" value="{{$bannerAdImages->order}}">
											</div>
										</div>													
										<div class="control-group">
											<label class="control-label" for="basicinput">Image</label>
											<div class="controls">
											<?php $url=url('BannerImage/'.$bannerAdImages->images); 
                                				?>
												<input type="file" name="images" id="basicinput" class="span8" value="{{ $bannerAdImages->images }}">
												<a href="{{ asset('/BannerImage/' .$bannerAdImages->images)}}"><img class="d-block w-100" src="{{$url}}"  alt="Snow" height="100px" width="100px"></a>

											</div>
										</div>	

										<div class="control-group">
											<label class="control-label" for="basicinput">Image Type</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="image_types">
													<option value="" disabled selected>Select here..</option>
													<option value="banner_ad_image" {{$bannerAdImages->image_types == 'banner_ad_image' ? 'selected' : '' }} >Banner Ad</option>
													<option value="slider_image" {{$bannerAdImages->image_types == 'slider_image' ? 'selected' : '' }}>Slider</option>
												</select>
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Sub Category Link Id</label>
											<div class="controls">
												<select tabindex="1" data-placeholder="Select here.." class="span8" name="sub_category_link_id">
													<option value="" disabled selected>Select here..</option>
													@foreach($subCategoryLists as $subCategoryList)
													<option value="{{$subCategoryList->id}}" {{ $subCategoryList->id=$bannerAdImages->sub_category_link_id? "selected" : ''}}>{{$subCategoryList->product_sub_category_name}}</option>
													@endforeach
												</select>
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="basicinput">Description</label>
											<div class="controls">
												<textarea class="span8" rows="5" name="description">{{$bannerAdImages->description}}</textarea>
											</div>
										</div>
										<div class="control-group">
											<div class="controls">
												<button type="submit" class="btn btn-primary">Update</button>
											</div>
										</div>
									</form>
							</div>
						</div>	
					</div><!--/.content-->
                </div><!--/.span9-->
        @endsection

resources/views/admin/pages/banner-ad-images/index.blade.php
@extends('admin.layouts.app')
@section('title','Product Category')
@section('content')


					<div class="row">
						<div class="col-lg-12" style="text-align: right;">
					<a href="{{route('admin.banner-ad-images.create')}}" class="btn btn-info">Create</a>
						</div>
					</div>
						<div class="module">
							<div class="module-head">
								<h3>Banner Add Images list</h3>
							</div>
							<div class="module-body table">
							@include('error-messages.message')

								<table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display" width="100%">
									<thead>
										<tr>
											<th>Image Name</th>
											<th>Order</th>
											<th>Image Type</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach($bannerAdImages as $bannerAdImage)
										<tr class="odd gradeX">
											<td>{{ $bannerAdImage->banner_add_name }}</td>
											<td>{{$bannerAdImage->order}}</td>
											<td>{{ $bannerAdImage->image_types }}</td>
											<td>
												<a href="{{route('admin.banner-ad-images.edit', $bannerAdImage->id)}}" class="btn btn-info">Edit</a>
											</td>
										</tr>	
										@endforeach
									</tbody>
								</table>
							</div>
						</div><!--/.module-->

					<br />
@endsection